In [1]:
import os
import numpy as np
from matplotlib import pyplot

def warmUpExercise():

	A=np.eye(5)
	return A
print warmUpExercise()

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
